data:
  name: megadepth
  views: 3
  preprocessing:
    resize: 768
    side: long
    interpolation: bilinear
    antialias: False
    align_corners: False
    square_pad: true
  train_split: disk_train_scenes.txt
  train_num_per_scene: 63
  val_split: disk_valid_scenes.txt
  val_num_per_scene: 250
  read_depth: true
  read_image: true
  num_workers: 10
  batch_size: 2
  min_overlap: 0.15
  max_overlap: 0.8
  triplet_enforce_overlap: false
  seed: 42
  load_features:
    do: False

model:
  name: triplet_pipeline
  extractor:
    name: disk
    max_num_keypoints: null
    force_num_keypoints: True
    detection_threshold: 0.0
    trainable: True
  batch_triplets: False

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 1000
  save_every_iter: 2500
  log_grad_every_iter: 1000
  keep_last_checkpoints: 30
  dataset_callback_fn: sample_new_items
  auc_metrics:
    desc_rel_pose_error: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  lr: 1e-4
  lr_schedule:
    type: null
  lr_scaling: [()]
  mixed_precision: False
  plot: [5, 'keypointfactory.visualization.visualize_batch.make_keypoint_figures']
  substep: 1

benchmarks:
  megadepth1500:
    data:
      num_workers: 10
    eval:
      top_k_thresholds: 500
      top_k_by: "scores"
      estimator: "degensac"
      ransac_th: 1.0
      use_depth: False
