data:
  name: homographies
  data_dir: revisitop1m
  train_size: 12000
  val_size: 1000
  batch_size: 2
  triplet: true
  num_workers: 8
  homography:
    difficulty: 0.7
    max_angle: 90
    patch_shape: [640, 480]
  photometric:
    name: lg

model:
  name: triplet_pipeline
  extractor:
    name: disk
    max_num_keypoints: null
    force_num_keypoints: true
    detection_threshold: 0.0
    trainable: true
    reward: homography
  batch_triplets: false
  enumerate_pairs: true

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 1000
  save_every_iter: 2500
  log_grad_every_iter: 2500
  test_every_epoch: 5
  keep_last_checkpoints: 30
  auc_metrics:
    desc_H_error: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  lr: 1e-4
  lr_schedule:
    type: null
  lr_scaling: [()]
  mixed_precision: false
  plot:
    [5, "keypointfactory.visualization.visualize_batch.make_keypoint_figures"]
  substep: 1

benchmarks:
  hpatches:
    data:
      num_workers: 10
    eval:
      top_k_thresholds: 2048
      top_k_by: "scores"
      estimator: "degensac"
      ransac_th: 1.0
      use_gt: true
      summarize_by_scene: true
