model:
    name: two_view_pipeline
    extractor:
        name: extractors.disk_kornia
        max_num_keypoints: 2048
        detection_threshold: 0.0
        nms_window_size: 5
        force_num_keypoints: true

benchmarks:
    hpatches:
        eval:
            top_k_thresholds: 2048
            top_k_by: scores
    megadepth1500:
        eval: 
            top_k_thresholds: 2048
            top_k_by: scores
            estimator: degensac
            ransac_th: 1.0
            use_depth: False