data:
  name: hpatches
  data_dir: hpatches-sequences-release
  batch_size: 2
  preprocessing:
    resize: 768
    side: long
    interpolation: bilinear
    antialias: False
    align_corners: False
    square_pad: true
  triplet: true

model:
  name: triplet_pipeline
  extractor:
    name: diskv2
    max_num_keypoints: null
    force_num_keypoints: true
    detection_threshold: 0.0
    trainable: true
    reward: homography
    loss:
      reward_threshold: 3
      score_type: coarse
      lm_c: 0.01
    arch:
      down: [16,32,64]
      up: [64,1]
      down_block: ResDownBlock
      up_block: ResUpBlock
  batch_triplets: false
  enumerate_pairs: true

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 270
  save_every_iter: 270
  log_grad_every_iter: 270
  best_key: loss/total
  auc_metrics:
    homography_H_error: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  lr: 1e-4
  lr_schedule:
    type: null
  lr_scaling: [()]
  mixed_precision: false
  plot:
    [5, "keypointfactory.visualization.visualize_batch.make_keypoint_figures"]
  substep: 1
  warmup: 0

benchmarks:
  hpatches:
    data:
      num_workers: 10
    eval:
      top_k_thresholds: 1024
      top_k_by: "scores"
      estimator: "degensac"
      ransac_th: 1.0
      use_gt: true
      summarize_by_scene: false
