data:
  name: hpatches
  data_dir: hpatches-sequences-release
  batch_size: 2
  preprocessing:
    resize: 768
    side: long
    interpolation: bilinear
    antialias: False
    align_corners: False
    square_pad: true

model:
  name: triplet_pipeline
  extractor:
    name: diskv2
    max_num_keypoints: null
    force_num_keypoints: True
    detection_threshold: 0.0
    trainable: True
    reward: homography
    loss:
      reward_threshold: 5
      lambda_kp: 0
  batch_triplets: False

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 270
  save_every_iter: 270
  log_grad_every_iter: 270
  best_key: loss/total
  auc_metrics:
    homography_H_error: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  lr: 1e-5
  lr_schedule:
    type: null
  lr_scaling: [()]
  mixed_precision: false
  plot:
    [5, "keypointfactory.visualization.visualize_batch.make_keypoint_figures"]
  substep: 1

benchmarks:
  hpatches:
    data:
      num_workers: 10
    eval:
      top_k_thresholds: 1024
      top_k_by: "scores"
      estimator: "degensac"
      ransac_th: 1.0
      use_gt: False
      summarize_by_scene: False