model:
    name: two_view_pipeline
    extractor:
        name: extractors.diskv2
        max_num_keypoints: null
        detection_threshold: 0.0
        nms_radius: 2
        force_num_keypoints: true

benchmarks:
    hpatches:
        eval:
            top_k_thresholds: 2048
            top_k_by: scores
            estimator: degensac
            ransac_th: 1.0
            use_gt: True
            summarize_by_scene: True
    megadepth1500:
        eval:
            top_k_thresholds: 2048
            top_k_by: scores
            estimator: degensac
            ransac_th: 1.0
            use_gt: True
            summarize_by_scene: True