data:
  name: megadepth
  views: 3
  preprocessing:
    resize: 768
    side: long
    interpolation: bilinear
    align_corners: False
    square_pad: true
  train_split: disk_train_scenes.txt
  train_num_per_scene: 5000
  val_split: disk_valid_scenes.txt
  val_num_per_scene: 1000
  read_depth: true
  read_image: true
  num_workers: 14
  batch_size: 2
  min_overlap: 0.0
  max_overlap: 1.0
  load_features:
    do: False

model:
  name: triplet_pipeline
  extractor:
    name: disk
    max_num_keypoints: null
    force_num_keypoints: True
    detection_threshold: 0.0
    trainable: True
  batch_triplets: False

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 500
  save_every_iter: 1000
  lr: 1e-4
  lr_schedule:
    type: null
  mixed_precision: False
  substep: 1