model:
    name: two_view_pipeline
    extractor:
        name: extractors.disk
        max_num_keypoints: null
        detection_threshold: 0.0
        nms_radius: 8
        force_num_keypoints: true
        weights: weights/save-21.pth

benchmarks:
    hpatches:
        data:
            preprocessing:
                resize: 768
                side: long
                interpolation: bilinear
                align_corners: False
                square_pad: true
        eval:
            top_k_thresholds: 500
            top_k_by: "scores"
    megadepth1500:
        data:
          num_workers: 12
          #preprocessing:
          #      resize: 768
          #      side: long
          #      interpolation: bilinear
          #      align_corners: False
          #      square_pad: true
        use_depth: true
        eval:
            top_k_thresholds: 500
            top_k_by: "scores"
            estimator: "degensac"
            ransac_th: 1.0
            use_depth: False
    imc2020:
        data:
            preprocessing:
                resize: 768
                side: long
                interpolation: bilinear
                align_corners: False
                square_pad: true
        eval:
            top_k_thresholds: 500
            top_k_by: "scores"
            estimator: "degensac"
            ransac_th: 1.0
            use_depth: False
