data:
  name: megadepth
  views: 3
  preprocessing:
    resize: 768
    side: long
    interpolation: bilinear
    antialias: false
    align_corners: false
    square_pad: true
  train_split: disk_train_scenes.txt
  train_num_per_scene: 62
  val_split: disk_valid_scenes.txt
  val_num_per_scene: 250
  read_depth: true
  read_image: true
  num_workers: 10
  batch_size: 2
  min_overlap: 0.15
  max_overlap: 0.8
  triplet_enforce_overlap: false
  seed: 42
  load_features:
    do: false

model:
  name: triplet_pipeline
  extractor:
    name: diskv2
    max_num_keypoints: null
    force_num_keypoints: true
    sample_budget: 2048
    trainable: True
    reward: depth
    arch:
      down: [16, 32, 64]
      up: [64, 1]
      down_block: ResDownBlock
      up_block: ResUpBlock
    loss:
      reward_threshold: 3
      score_type: coarse
      lm_e: 0.01
  batch_triplets: false
  enumerate_pairs: true

train:
  seed: 42
  epochs: 50
  log_every_iter: 100
  eval_every_iter: 2500
  save_every_iter: 2500
  log_grad_every_iter: 2500
  test_every_epoch: 5
  keep_last_checkpoints: 30
  dataset_callback_fn: sample_new_items
  auc_metrics:
    depth_rel_pose_error: [1, 3, 5]
  lr: 1e-4
  lr_schedule:
    type: null
  lr_scaling: [()]
  mixed_precision: false
  plot: [5, 'keypointfactory.visualization.visualize_batch.make_keypoint_figures']
  substep: 1

benchmarks:
  megadepth1500:
    model:
      extractor:
        max_num_keypoints: 2048
    data:
      num_workers: 10
    eval:
      top_k_thresholds: 1024
      top_k_by: "scores"
      estimator: "degensac"
      ransac_th: 1.0
      use_depth: false
      summarize_by_scene: false
