model:
    name: two_view_pipeline
    extractor:
        name: extractors.sift
        detector: pycolmap_cuda
        max_num_keypoints: 2048
        detection_threshold: 0.00666666
        nms_radius: -1
        pycolmap_options:
            first_octave: -1

benchmarks:
    hpatches:
        eval:
            estimator: opencv
            ransac_th: 0.5
        model:
            extractor:
                max_num_keypoints: 1024  # overwrite config above
            matcher:
                name: matchers.homography_matcher
                th_positive: 3.0
                th_negative: 3.0
    megadepth:
        eval: 
            estimator: opencv
            ransac_th: 0.5
        model:
            extractor:
                max_num_keypoints: 1024
            matcher:
                name: matchers.depth_matcher
                th_positive: 3.0
                th_negative: 5.0
                th_epi: None
                th_consistency: None