model:
    name: two_view_pipeline
    extractor:
        name: extractors.superpoint_open
        max_num_keypoints: 2048
        detection_threshold: 0.0
        nms_radius: 3

benchmarks:
    hpatches:
        eval:
            top_k_thresholds: 2048
            top_k_by: scores
    megadepth1500:
        eval: 
            top_k_thresholds: 2048
            top_k_by: scores
            estimator: degensac
            ransac_th: 1.0
            use_depth: False